apiVersion: apps/v1
kind: Deployment
metadata:
  name: naam-dev-api-backend-test
  namespace: test
  labels:
    type: dev
    server-type: naam-dev-api-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: dev
      server-type: naam-dev-api-backend
  template:
    metadata:
      labels:
        type: dev
        server-type: naam-dev-api-backend
    spec:
      nodeSelector:
          node-role.kubernetes.io/worker: w1
      #volumes:                    # Add the "volumes" section
       # - name: naam-dev-api-backend          # Define the volume name
          #persistentVolumeClaim:
            #claimName: naam-dev-api-backend    # Specify the name of the PersistedntVolumeClaim (PVC) to bind to
      containers:
        - name: naam-dev-api-backend
          image:  dev-registry.sarv.com/naam-dev/helloapp:$TAG
          #volumeMounts:           # Add the "volumeMounts" section
            #- name: naam-dev-api-backend      # Reference the volume name defined above
              #mountPath: /app      # Mount the volume at the desired path inside the container
          resources:
            limits:
              memory: 1Gi
              cpu: "2"
            requests:
              memory: 128Mi
              cpu: "0.5"
      imagePullSecrets:
        - name: imgcred1
