apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

images:
  - name: dev-registry.sarv.com/naam-dev/naam-dev-api-backend
    newName: dev-registry.sarv.com/naam-dev/naam-dev-api-backend
    newTag: $TAG
